function DefineAllTheItems() {Elements = []
Events = ["On World Load",
    "On World Tick"];

Functions = ["Kill <player/selector>",
    "Kill <entity>",
    "Spawn <entity> ~<x> ~<y> ~<z> with <tags>",
    "Spawn <var custom entity> ~<x> ~<y> ~<z> with <tags>",
    "Give <player/selector> <count>x <item>",
    "Give <player/selector> <count>x <var custom item>",
    "Place <block> ~<x> ~<y> ~<z>",
    "Set time to <time>",
    "Run The Next <number> Command At ~<x> ~<y> ~<z>",
    "Run The Next <number> Command At ^<x> ^<y> ^<z>",
    "Run The Next <number> Command At <x> <y> <z>",
    "Run The Next <number> Command From <entity>",
    "Run The Next <number> Command From <player/selector>",
    "Teleport <player/selector> ~<x> ~<y> ~<z>",
    "Teleport <entity> ~<x> ~<y> ~<z>",
    "Send message in chat, visible for <player/selector>: <message>",
    "Display on <player/selector>'s screen as title: <message>",
    "Display on <player/selector>'s screen as subtitle: <message>",
    "Display on <player/selector>'s screen as actionbar: <message>",
    "Apply Force ~<number> ~<number> ~<number> to <entity>",
    "Apply Force to <entity> in the direction of <entity> with power factor <number>",
    "Apply Force to <entity> in the direction of <player/selector> with power factor <number>",
    "Run Command: <command>",
    "Create a explosion with power <number>",
    "Spawn a fireball with explosion <number> and tags are <tags>",
    "Give the effect <effect> <amplifier> for <duration> to the <player/selector>",
    "Give the effect <effect> <amplifier> for <duration> to the <entity>",
    "Clear the effect <effect> from <player/selector>",
    "Clear the effect <effect> from <entity>",
    "Create an area of cloud giving effect <effect> <amplifier> for <duration> with particle being <particle> and in the radius of <number> and tags are <tags>"];

Informations = ["<var number> = <player/selector>'s Health",
    "<var number> = <player/selector>'s Food",
    "<var number> = <player/selector>'s Death Count",
    "<var number> = <player/selector> Amount of dealt damage",
    "<var number> = <player/selector> Amount of taken damage",
    "<var number> = <player/selector> Amount of jump",
    "<var number> = <player/selector> used <item>",
];

Variables = ["Define <var number> as <number>",
    "<var number> += <var number>",
    "<var number> -= <var number>",
    "<var number> *= <var number>",
    "<var number> /= <var number>",
    "<var number> = if [<var number> = <var number>]",
    "<var number> = if [<var number> > <var number>]",
    "<var number> = if [<var number> < <var number>]",
    "<var number> = if [<entity> exists]",
    "<var number> = if [block at ~<x> ~<y> ~<z> is <block>]",
    "<var number> = if [biome at ~<x> ~<y> ~<z> is <biome>]",
    "Define <var custom item> as <item name>",
    "<var custom item>'s name = <name>",
    "<var custom item>'s enchantments += <enchantment name> <enchantment level>",
    "<var custom item>'s lore += <lore>",
    "<var custom item> is unbreakable = <yes/no>",
    "<var custom item> invisible enchantments = <yes/no>",
    "<var custom item> damage = <number>",
    "Define <var custom entity> as <entity>",
    "<var custom entity>'s name = <name>",
    "<var custom entity> is silent = <yes/no>",
    "<var custom entity> is giving a ride to <entity>",
    "<var custom entity> is holding <mainhand> and <offhand>",
    "<var custom entity> is wearing <boots> and <leggings> and <chestplate> and <helmet>"
];
                                    
Loops = [
    "If <var> run the next <number> command",
    "Unless <var> run the next <number> command"];}